steps:
- name: ubuntu
  args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
- name: gcr.io/poc-dna-automation-693335/macydemo
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${demo12trial}/dags'
- name: gcr.io/poc-dna-automation-693335/macydemo
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'plugins'
    - 'gs://${demo12trial}/plugins'
  # Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
