steps:
- name: ubuntu
- name: 'gcr.io/poc-dna-automation-693335/gcr_demo_pract1'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${_GCS_BUCKET}/dags'
- name: 'gcr.io/poc-dna-automation-693335/gcr_demo_pract1'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'plugins'
    - 'gs://${_GCS_BUCKET}/plugins'
#Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
