steps:
- name: 'gcr.io/cloud-builders/javac'
  args: ['HelloWorld.java']
artifacts:
  objects:
    location: 'gs://demo12trial/demo/'
    paths: ['HelloWorld.java', 'HelloWorld.class', 'cloudbuild.yaml']
   # Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
