steps:
- name: ubuntu
  args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
- name: 'gcr.io/poc-dna-automation-693335/macydemo'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${_GCS_BUCKET}/dags'
- name: 'gcr.io/poc-dna-automation-693335/macydemo'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'plugins'
    - 'gs://${_GCS_BUCKET}/plugins'
 # Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
