steps:
- name: ubuntu
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${_GCS_BUCKET_1}./dags'
    #Logging
options:
  logging: CLOUD_LOGGING_ONLY
#completed
