steps:
- name: gcr.io/poc-dna-automation-693335/macydemo
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - './dags'
- name: gcr.io/poc-dna-automation-693335/macydemo
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'plugins'
    - 'gs://gs://demo12trial'
  # Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
