name: 'Google Cloud Storage Bucket Sync'
description: 'Sync a Github repository with a Google Cloud Storage (GCS) bucket'
author: 'PM'

inputs:
  secrets:
    description: Google credentials
    required: true
  bucket:
    description: demo12trial
    required: true
  exclude:
    description: Regex for excluding files/dirs
    required: false
    default: '.git$'

runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up
  color: gray-dark
